"""
Generator for the ep_2026_cleaned Airtable union views.

Renders CREATE OR REPLACE VIEW statements that UNION each registered base's
typed tables (ep_2026_raw.{prefix}__{table}) into one cross-state view per
entity: quiz_responses, incident_reports, checklist_submissions,
polling_places, shifted_volunteers.

Inputs, resolved live at render time:
  - the base registry (ep.airtable_sync_sources, enabled rows) -- provides
    state, base_type, prefix, and per-base canonical_overrides JSON;
  - ep_2026_raw.INFORMATION_SCHEMA.COLUMNS -- which columns each typed
    table actually landed with (and their types, so casts are exact);
  - the per-entity canonical contracts below (DEFAULT source-column
    candidates, auto-heuristics, link-resolution fallbacks).

Per canonical column, source resolution order:
  registry canonical_overrides -> default candidates -> regex heuristic ->
  record-link fallback -> NULL-pad (CAST(NULL AS T)).

canonical_overrides shape (JSON on the registry row):
  {"<entity>": {"<canonical_col>": "<sanitized_source_col>" | null}}
String forces the source column; null removes (NULL-pads) the column for
that base. Overrides bypass candidates/heuristics but keep transforms/casts.

Entities with no live base render as the full contract + WHERE FALSE, so
consumers can build against the schema before any base goes live.

Used two ways:
  - sync_airtable_bases.py calls render + apply at the end of each run
    (a base going live updates the unions the same morning);
  - apply_bq_views.py --render-generated rewrites the committed
    bq/ep_2026_cleaned/3x_*.sql snapshots for review/commit.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from ccef_connections import BigQueryConnector

PROJECT = "proj-tmc-mem-com"
RAW_DATASET = "ep_2026_raw"
CLEAN_DATASET = "ep_2026_cleaned"
SOURCES_TABLE = f"{PROJECT}.ep.airtable_sync_sources"
USERS_CURRENT_VIEW = f"{PROJECT}.ptv_raw_2026.v_users_current"
SQL_DIR = Path(__file__).parent / "bq" / CLEAN_DATASET

NORM_EMAIL = f"`{PROJECT}.{CLEAN_DATASET}.norm_email`"
NORM_PHONE = f"`{PROJECT}.{CLEAN_DATASET}.norm_phone`"

GENERATED_HEADER = (
    "-- GENERATED by airtable_views.py -- DO NOT HAND-EDIT.\n"
    "-- Regenerate with: python apply_bq_views.py --render-generated\n"
    "-- (sync_airtable_bases.py also re-applies these after every run, so a\n"
    "-- base going live is included the same morning; refresh + commit this\n"
    "-- snapshot as part of the go-live checklist.)\n"
)

logger = logging.getLogger(__name__)


# -- Entity contracts ---------------------------------------------------------


@dataclass
class Link:
    """Record-link fallback: resolve a column off a linked record."""
    via: List[str]        # candidate link columns (JSON id-array strings)
    target_key: str       # table_key of the link target within the same base
    target_col: str       # column to take from the target table
    alias: str            # stable join alias


@dataclass
class Col:
    name: str
    bq_type: str                              # STRING | INT64 | BOOL | TIMESTAMP
    sources: List[str] = field(default_factory=list)
    transform: Optional[str] = None           # 'norm_email' | 'norm_phone'
    regex_source: Optional[str] = None        # value column matched by pattern
    regex_capture: Optional[str] = None       # literal INT from pattern capture
    link: Optional[Link] = None               # fallback when no source present
    computed: Optional[str] = None            # special-cased in _branch_select


@dataclass
class Entity:
    view: str
    table_keys: List[str]                     # typed-table suffixes that feed it
    base_types: List[str]
    description: str
    columns: List[Col]


_SV_LINK = dict(via=["volunteer", "shifted_volunteers", "shifted_volunteers_copy"],
                target_key="shifted_volunteers", alias="sv")
_PP_LINK = dict(via=["polling_places"], target_key="polling_places", alias="pp")

ENTITIES: List[Entity] = [
    Entity(
        view="quiz_responses",
        table_keys=["quiz_responses"],
        base_types=["quiz"],
        description=(
            "All 2026 EP quiz responses across state quiz bases (registry: "
            "ep.airtable_sync_sources, base_type='quiz'). One row per Airtable "
            "record. score/score_max derive from the per-base grader column "
            "'correct_answers_out_of_{n}'; passed = score = score_max. "
            "Per-question answers stay in the ep_2026_raw typed tables / "
            "airtable_records_latest JSON. email normalized via norm_email. "
            "state comes from the registry, never from record fields."
        ),
        columns=[
            Col("email", "STRING", sources=["email"], transform="norm_email"),
            Col("email_raw", "STRING", sources=["email"]),
            Col("full_name", "STRING", sources=["full_name"]),
            Col("score", "INT64", regex_source=r"^correct_answers_out_of_(\d+)$"),
            Col("score_max", "INT64", regex_capture=r"^correct_answers_out_of_(\d+)$"),
            Col("passed", "BOOL", computed="passed"),
            Col("role_id", "INT64", sources=["role_id"]),
            Col("role_id_2", "INT64", sources=["role_id_2"]),
            Col("shift_type", "STRING",
                sources=["shift", "what_type_of_poll_shift_do_you_want"]),
        ],
    ),
    Entity(
        view="incident_reports",
        table_keys=["incident_reports"],
        base_types=["field_report"],
        description=(
            "All 2026 EP field incident reports across state field-report "
            "bases. One row per Airtable record. Canonical columns cover the "
            "reporter, category, location, and narrative; state-specific "
            "fields (incl. subcategories and any voter-identifying fields, "
            "which are deliberately NOT canonicalized) stay in the "
            "ep_2026_raw typed tables / airtable_records_latest JSON. "
            "volunteer_email normalized via norm_email; state comes from the "
            "registry."
        ),
        columns=[
            Col("report_id", "INT64", sources=["report_id"]),
            Col("volunteer_name", "STRING", sources=["volunteer_name"]),
            Col("volunteer_first_name", "STRING", sources=["volunteer_first_name"]),
            Col("volunteer_last_name", "STRING", sources=["volunteer_last_name"]),
            Col("volunteer_email", "STRING", sources=["volunteer_email"],
                transform="norm_email"),
            Col("volunteer_email_raw", "STRING", sources=["volunteer_email"]),
            Col("volunteer_phone", "STRING", sources=["volunteer_s_phone_number"],
                transform="norm_phone"),
            Col("source", "STRING", sources=["source"]),
            Col("caller", "STRING", sources=["caller"]),
            Col("category", "STRING", sources=["voting_issue_category"]),
            Col("voting_method", "STRING", sources=["voting_method"]),
            Col("polling_place_name", "STRING",
                sources=["polling_place_name_from_polling_place"]),
            Col("county", "STRING", sources=["county_from_polling_place"]),
            Col("description", "STRING", sources=["notes_comments"]),
            Col("requires_escalation", "BOOL", sources=["requires_escalation"]),
            Col("escalation_resolved", "BOOL", sources=["escalation_resolved"]),
            Col("escalation_notes", "STRING", sources=["escalation_notes"]),
        ],
    ),
    Entity(
        view="checklist_submissions",
        table_keys=["checklist_submissions", "poll_monitoring_checklist"],
        base_types=["field_report"],
        description=(
            "All 2026 EP polling-place checklist submissions across state "
            "field-report bases (stock 'Checklist Submissions' tables plus "
            "bespoke variants like UT's 'Poll Monitoring Checklist'). One row "
            "per Airtable record. Volunteer identity resolves from direct "
            "fields where the base has them, else via the volunteer record "
            "link into that base's Shifted Volunteers table. Per-question "
            "answers are NEVER canonicalized across states -- read them from "
            "the ep_2026_raw typed tables / airtable_records_latest JSON. "
            "state comes from the registry."
        ),
        columns=[
            Col("volunteer_email", "STRING", sources=["volunteer_email"],
                transform="norm_email",
                link=Link(target_col="email", **_SV_LINK)),
            Col("volunteer_email_raw", "STRING", sources=["volunteer_email"],
                link=Link(target_col="email", **_SV_LINK)),
            Col("volunteer_name", "STRING", sources=["volunteer_name"],
                link=Link(target_col="full_name", **_SV_LINK)),
            Col("volunteer_phone", "STRING", sources=["volunteer_phone"],
                transform="norm_phone",
                link=Link(target_col="phone_number", **_SV_LINK)),
            Col("polling_place", "STRING", sources=["polling_place"],
                link=Link(target_col="polling_place", **_PP_LINK)),
            Col("county", "STRING", sources=["county"],
                link=Link(target_col="county", **_PP_LINK)),
            Col("checklist_name", "STRING", sources=["polling_place_checklist"]),
        ],
    ),
    Entity(
        view="polling_places",
        table_keys=["polling_places"],
        base_types=["field_report"],
        description=(
            "All polling places loaded into the state field-report bases "
            "(CC-loaded reference data plus any field additions). One row per "
            "Airtable record. state comes from the registry."
        ),
        columns=[
            Col("name", "STRING", sources=["polling_place"]),
            Col("pp_name", "STRING", sources=["pp_name"]),
            Col("address", "STRING", sources=["address"]),
            Col("city", "STRING", sources=["city"]),
            Col("zip_code", "STRING", sources=["zip"]),
            Col("county", "STRING", sources=["county"]),
            Col("notes", "STRING", sources=["location_notes"]),
        ],
    ),
    Entity(
        view="shifted_volunteers",
        table_keys=["shifted_volunteers"],
        base_types=["field_report"],
        description=(
            "All records in the state bases' 'Shifted Volunteers' tables "
            "(dual write paths: the PTV sync upsert + the emergency self-add "
            "form). One row per Airtable record. in_ptv flags whether the "
            "(state, email) exists in PTV's CURRENT roster "
            "(ptv_raw_2026.v_users_current) -- FALSE means a self-add with no "
            "PTV counterpart yet. Feeds the volunteers view's self-add "
            "branch; also useful for sync reconciliation. email/phone "
            "normalized; state comes from the registry."
        ),
        columns=[
            Col("email", "STRING", sources=["email"], transform="norm_email"),
            Col("email_raw", "STRING", sources=["email"]),
            Col("first_name", "STRING", sources=["first_name"]),
            Col("last_name", "STRING", sources=["last_name"]),
            Col("full_name", "STRING", sources=["full_name"]),
            Col("phone", "STRING", sources=["phone_number"], transform="norm_phone"),
            Col("county", "STRING", sources=["county"]),
            Col("zip_code", "STRING", sources=["zip"]),
            Col("unique_id", "STRING", sources=["unique_id_column"]),
            Col("in_ptv", "BOOL", computed="in_ptv"),
        ],
    ),
]

# filename snapshots: 30-34 (before 40_volunteers, which reads shifted_volunteers)
ENTITY_FILES: Dict[str, str] = {
    "quiz_responses": "30_quiz_responses.sql",
    "incident_reports": "31_incident_reports.sql",
    "checklist_submissions": "32_checklist_submissions.sql",
    "polling_places": "33_polling_places.sql",
    "shifted_volunteers": "34_shifted_volunteers.sql",
}


# -- Inputs -------------------------------------------------------------------


@dataclass
class RegistryRow:
    name: str
    state: str
    base_id: str
    base_type: str
    prefix: str
    overrides: Dict[str, Dict[str, Optional[str]]]


def load_registry(bq: BigQueryConnector) -> List[RegistryRow]:
    sql = f"""
        SELECT name, state, base_id, base_type, bq_table_prefix,
               TO_JSON_STRING(canonical_overrides) AS overrides_json
        FROM `{SOURCES_TABLE}`
        WHERE enabled = TRUE
        ORDER BY bq_table_prefix
    """
    rows: List[RegistryRow] = []
    for r in bq.query(sql):
        raw = r["overrides_json"]
        overrides = json.loads(raw) if raw and raw != "null" else {}
        rows.append(RegistryRow(
            name=r["name"], state=r["state"], base_id=r["base_id"],
            base_type=r["base_type"], prefix=r["bq_table_prefix"],
            overrides=overrides or {},
        ))
    return rows


def load_landed_columns(bq: BigQueryConnector) -> Dict[str, Dict[str, str]]:
    """{typed_table_name: {column: data_type}} for all of ep_2026_raw."""
    sql = f"""
        SELECT table_name, column_name, data_type
        FROM `{PROJECT}.{RAW_DATASET}.INFORMATION_SCHEMA.COLUMNS`
    """
    out: Dict[str, Dict[str, str]] = {}
    for r in bq.query(sql):
        out.setdefault(r["table_name"], {})[r["column_name"]] = r["data_type"]
    return out


# -- Rendering ----------------------------------------------------------------


def _cast(expr: str, landed_type: Optional[str], target: str) -> str:
    """Exact minimal cast from the landed BQ type to the target type."""
    if landed_type == target:
        return expr
    if target == "STRING":
        return f"CAST({expr} AS STRING)"
    if target == "INT64":
        if landed_type == "FLOAT64":
            return f"SAFE_CAST({expr} AS INT64)"
        return f"SAFE_CAST(SAFE_CAST({expr} AS FLOAT64) AS INT64)"
    if target == "BOOL":
        return f"SAFE_CAST(CAST({expr} AS STRING) AS BOOL)"
    if target == "TIMESTAMP":
        return f"SAFE_CAST(CAST({expr} AS STRING) AS TIMESTAMP)"
    return f"SAFE_CAST({expr} AS {target})"


def _wrap_transform(expr: str, transform: Optional[str]) -> str:
    if transform == "norm_email":
        return f"{NORM_EMAIL}({expr})"
    if transform == "norm_phone":
        return f"{NORM_PHONE}({expr})"
    return expr


def _resolve_col(
    col: Col,
    entity: Entity,
    row: RegistryRow,
    table_cols: Dict[str, str],
    landed: Dict[str, Dict[str, str]],
    joins: Dict[str, Tuple[str, str]],   # alias -> (link_col, target_table)
) -> str:
    """Return the SELECT expression for one canonical column in one branch."""
    null_expr = f"CAST(NULL AS {col.bq_type})"

    # 1. Registry override (string forces source; null forces NULL-pad).
    ov = row.overrides.get(entity.view, {})
    if col.name in ov:
        source = ov[col.name]
        if source is None:
            return null_expr
        if source not in table_cols:
            logger.warning(
                f"[{row.prefix}] override {entity.view}.{col.name} -> "
                f"'{source}' not in landed columns -- NULL-padding"
            )
            return null_expr
        expr = _cast(f"t.`{source}`", table_cols[source], "STRING"
                     if col.transform else col.bq_type)
        return _wrap_transform(expr, col.transform)

    # 2. Computed columns (special-cased per entity; handled by caller).
    if col.computed:
        return ""  # placeholder -- caller substitutes

    # 3. Regex capture -> literal from the matching column NAME.
    if col.regex_capture:
        pat = re.compile(col.regex_capture)
        for c in sorted(table_cols):
            m = pat.match(c)
            if m:
                return f"CAST({int(m.group(1))} AS INT64)"
        return null_expr

    # 4. Regex-matched value column.
    if col.regex_source:
        pat = re.compile(col.regex_source)
        for c in sorted(table_cols):
            if pat.match(c):
                return _cast(f"t.`{c}`", table_cols[c], col.bq_type)
        return null_expr

    # 5. Direct candidates, first present wins.
    for c in col.sources:
        if c in table_cols:
            expr = _cast(f"t.`{c}`", table_cols[c], "STRING"
                         if col.transform else col.bq_type)
            return _wrap_transform(expr, col.transform)

    # 6. Record-link fallback.
    if col.link:
        target_table = f"{row.prefix}__{col.link.target_key}"
        if target_table in landed and col.link.target_col in landed[target_table]:
            for via in col.link.via:
                if via in table_cols:
                    joins[col.link.alias] = (via, target_table)
                    t_type = landed[target_table][col.link.target_col]
                    expr = _cast(
                        f"{col.link.alias}.`{col.link.target_col}`",
                        t_type,
                        "STRING" if col.transform else col.bq_type,
                    )
                    return _wrap_transform(expr, col.transform)
        return null_expr

    return null_expr


def _branch_sql(
    entity: Entity,
    row: RegistryRow,
    table_name: str,
    landed: Dict[str, Dict[str, str]],
) -> str:
    table_cols = landed[table_name]
    joins: Dict[str, Tuple[str, str]] = {}

    exprs: Dict[str, str] = {}
    for col in entity.columns:
        exprs[col.name] = _resolve_col(col, entity, row, table_cols, landed, joins)

    # Computed columns.
    for col in entity.columns:
        if col.computed == "passed":
            score, score_max = exprs.get("score"), exprs.get("score_max")
            if score and score_max and "NULL" not in (score, score_max):
                exprs[col.name] = f"({score}) = ({score_max})"
            else:
                exprs[col.name] = "CAST(NULL AS BOOL)"
        elif col.computed == "in_ptv":
            email = exprs.get("email") or "CAST(NULL AS STRING)"
            exprs[col.name] = (
                f"EXISTS(SELECT 1 FROM `{USERS_CURRENT_VIEW}` u "
                f"WHERE u.state = '{row.state}' AND u.email = {email})"
            )

    lines = [
        f"  '{row.state}' AS state,",
        f"  '{row.prefix}' AS base_key,",
        f"  '{row.base_id}' AS base_id,",
        "  t._airtable_record_id AS record_id,",
        "  t._airtable_created_time AS created_at,",
        "  t._synced_at AS synced_at,",
    ]
    lines += [f"  {exprs[c.name]} AS {c.name}," for c in entity.columns]
    lines[-1] = lines[-1].rstrip(",")

    sql = "SELECT\n" + "\n".join(lines)
    sql += f"\nFROM `{PROJECT}.{RAW_DATASET}.{table_name}` t"
    for alias in sorted(joins):
        link_col, target_table = joins[alias]
        sql += (
            f"\nLEFT JOIN `{PROJECT}.{RAW_DATASET}.{target_table}` {alias}"
            f"\n  ON {alias}._airtable_record_id = JSON_VALUE(t.`{link_col}`, '$[0]')"
        )
    return sql


def _bootstrap_sql(entity: Entity) -> str:
    """Full-contract empty branch so the view exists before any base does."""
    lines = [
        "  CAST(NULL AS STRING) AS state,",
        "  CAST(NULL AS STRING) AS base_key,",
        "  CAST(NULL AS STRING) AS base_id,",
        "  CAST(NULL AS STRING) AS record_id,",
        "  CAST(NULL AS TIMESTAMP) AS created_at,",
        "  CAST(NULL AS TIMESTAMP) AS synced_at,",
    ]
    lines += [f"  CAST(NULL AS {c.bq_type}) AS {c.name}," for c in entity.columns]
    lines[-1] = lines[-1].rstrip(",")
    return "SELECT\n" + "\n".join(lines) + "\nWHERE FALSE"


def render_entity_views(bq: BigQueryConnector) -> Dict[str, str]:
    """Render all union views. Returns {snapshot_filename: full_sql}."""
    registry = load_registry(bq)
    landed = load_landed_columns(bq)

    out: Dict[str, str] = {}
    for entity in ENTITIES:
        branches: List[str] = []
        for row in registry:
            if row.base_type not in entity.base_types:
                continue
            for key in entity.table_keys:
                table_name = f"{row.prefix}__{key}"
                if table_name in landed:
                    branches.append(_branch_sql(entity, row, table_name, landed))
        body = "\nUNION ALL\n".join(branches) if branches else _bootstrap_sql(entity)
        description = entity.description.replace('"', "'")
        sql = (
            f"{GENERATED_HEADER}\n"
            f"CREATE OR REPLACE VIEW `{PROJECT}.{CLEAN_DATASET}.{entity.view}`\n"
            f'OPTIONS(description="{description}")\n'
            f"AS\n{body};\n"
        )
        out[ENTITY_FILES[entity.view]] = sql
        logger.info(
            f"[views] {entity.view}: {len(branches)} branch(es)"
            + ("" if branches else " (bootstrap WHERE FALSE)")
        )
    return out


def write_snapshots(views: Dict[str, str]) -> None:
    for fname, sql in views.items():
        (SQL_DIR / fname).write_text(sql, encoding="utf-8", newline="\n")
        logger.info(f"[views] wrote {fname}")


def apply_views(bq: BigQueryConnector, views: Dict[str, str]) -> None:
    for fname in sorted(views):
        bq.query(views[fname])
        logger.info(f"[views] applied {fname}")


def render_write_apply(bq: BigQueryConnector) -> None:
    """The post-sync hook: regenerate, snapshot to disk, and deploy."""
    views = render_entity_views(bq)
    write_snapshots(views)
    apply_views(bq, views)
