-- GENERATED by airtable_views.py -- DO NOT HAND-EDIT.
-- Regenerate with: python apply_bq_views.py --render-generated
-- (sync_airtable_bases.py also re-applies these after every run, so a
-- base going live is included the same morning; refresh + commit this
-- snapshot as part of the go-live checklist.)

CREATE OR REPLACE VIEW `proj-tmc-mem-com.ep_2026_cleaned.quiz_responses`
OPTIONS(description="All 2026 EP quiz responses across state quiz bases (registry: ep.airtable_sync_sources, base_type='quiz'). One row per Airtable record. score/score_max derive from the per-base grader column 'correct_answers_out_of_{n}'; passed = score = score_max. Per-question answers stay in the ep_2026_raw typed tables / airtable_records_latest JSON. email normalized via norm_email. state comes from the registry, never from record fields.")
AS
SELECT
  'MI' AS state,
  'mi_poll_monitor_quiz' AS base_key,
  'appS6G8BSqMM1Ho2a' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`full_name` AS full_name,
  t.`correct_answers_out_of_7` AS score,
  CAST(7 AS INT64) AS score_max,
  (t.`correct_answers_out_of_7`) = (CAST(7 AS INT64)) AS passed,
  SAFE_CAST(t.`role_id` AS INT64) AS role_id,
  CAST(NULL AS INT64) AS role_id_2,
  t.`shift` AS shift_type
FROM `proj-tmc-mem-com.ep_2026_raw.mi_poll_monitor_quiz__quiz_responses` t
UNION ALL
SELECT
  'MI' AS state,
  'mi_rover_quiz' AS base_key,
  'appwb0e1CaVbTOBFm' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`full_name` AS full_name,
  t.`correct_answers_out_of_7` AS score,
  CAST(7 AS INT64) AS score_max,
  (t.`correct_answers_out_of_7`) = (CAST(7 AS INT64)) AS passed,
  SAFE_CAST(t.`role_id` AS INT64) AS role_id,
  CAST(NULL AS INT64) AS role_id_2,
  t.`shift` AS shift_type
FROM `proj-tmc-mem-com.ep_2026_raw.mi_rover_quiz__quiz_responses` t
UNION ALL
SELECT
  'NY' AS state,
  'ny_quiz' AS base_key,
  'appCpQYy3YBtGLFKb' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`full_name` AS full_name,
  t.`correct_answers_out_of_4` AS score,
  CAST(4 AS INT64) AS score_max,
  (t.`correct_answers_out_of_4`) = (CAST(4 AS INT64)) AS passed,
  SAFE_CAST(t.`role_id` AS INT64) AS role_id,
  SAFE_CAST(t.`role_id_2` AS INT64) AS role_id_2,
  CAST(NULL AS STRING) AS shift_type
FROM `proj-tmc-mem-com.ep_2026_raw.ny_quiz__quiz_responses` t
UNION ALL
SELECT
  'OR' AS state,
  'or_dropbox_quiz' AS base_key,
  'app8xBuT9zyUo0S28' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`full_name` AS full_name,
  SAFE_CAST(SAFE_CAST(t.`correct_answers_out_of_5` AS FLOAT64) AS INT64) AS score,
  CAST(5 AS INT64) AS score_max,
  (SAFE_CAST(SAFE_CAST(t.`correct_answers_out_of_5` AS FLOAT64) AS INT64)) = (CAST(5 AS INT64)) AS passed,
  SAFE_CAST(t.`role_id` AS INT64) AS role_id,
  CAST(NULL AS INT64) AS role_id_2,
  CAST(NULL AS STRING) AS shift_type
FROM `proj-tmc-mem-com.ep_2026_raw.or_dropbox_quiz__quiz_responses` t
UNION ALL
SELECT
  'OR' AS state,
  'or_quiz' AS base_key,
  'appEyPXAVmRHUkRv2' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`full_name` AS full_name,
  t.`correct_answers_out_of_5` AS score,
  CAST(5 AS INT64) AS score_max,
  (t.`correct_answers_out_of_5`) = (CAST(5 AS INT64)) AS passed,
  SAFE_CAST(t.`role_id` AS INT64) AS role_id,
  CAST(NULL AS INT64) AS role_id_2,
  CAST(NULL AS STRING) AS shift_type
FROM `proj-tmc-mem-com.ep_2026_raw.or_quiz__quiz_responses` t
UNION ALL
SELECT
  'OR' AS state,
  'or_trusted_messenger_quiz' AS base_key,
  'appQEJiaDCKt0SKEA' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`full_name` AS full_name,
  SAFE_CAST(SAFE_CAST(t.`correct_answers_out_of_3` AS FLOAT64) AS INT64) AS score,
  CAST(3 AS INT64) AS score_max,
  (SAFE_CAST(SAFE_CAST(t.`correct_answers_out_of_3` AS FLOAT64) AS INT64)) = (CAST(3 AS INT64)) AS passed,
  SAFE_CAST(t.`role_id` AS INT64) AS role_id,
  CAST(NULL AS INT64) AS role_id_2,
  CAST(NULL AS STRING) AS shift_type
FROM `proj-tmc-mem-com.ep_2026_raw.or_trusted_messenger_quiz__quiz_responses` t
UNION ALL
SELECT
  'PA' AS state,
  'pa_quiz' AS base_key,
  'appHu5TQJ0prMJncn' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`full_name` AS full_name,
  t.`correct_answers_out_of_3` AS score,
  CAST(3 AS INT64) AS score_max,
  (t.`correct_answers_out_of_3`) = (CAST(3 AS INT64)) AS passed,
  SAFE_CAST(t.`role_id` AS INT64) AS role_id,
  SAFE_CAST(t.`role_id_2` AS INT64) AS role_id_2,
  t.`what_type_of_poll_shift_do_you_want` AS shift_type
FROM `proj-tmc-mem-com.ep_2026_raw.pa_quiz__quiz_responses` t
UNION ALL
SELECT
  'UT' AS state,
  'ut_quiz' AS base_key,
  'appJFl1L0WuZR3ZpP' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`full_name` AS full_name,
  SAFE_CAST(SAFE_CAST(t.`correct_answers_out_of_7` AS FLOAT64) AS INT64) AS score,
  CAST(7 AS INT64) AS score_max,
  (SAFE_CAST(SAFE_CAST(t.`correct_answers_out_of_7` AS FLOAT64) AS INT64)) = (CAST(7 AS INT64)) AS passed,
  SAFE_CAST(t.`role_id` AS INT64) AS role_id,
  SAFE_CAST(t.`role_id_2` AS INT64) AS role_id_2,
  CAST(NULL AS STRING) AS shift_type
FROM `proj-tmc-mem-com.ep_2026_raw.ut_quiz__quiz_responses` t;
