-- GENERATED by airtable_views.py -- DO NOT HAND-EDIT.
-- Regenerate with: python apply_bq_views.py --render-generated
-- (sync_airtable_bases.py also re-applies these after every run, so a
-- base going live is included the same morning; refresh + commit this
-- snapshot as part of the go-live checklist.)

CREATE OR REPLACE VIEW `proj-tmc-mem-com.ep_2026_cleaned.incident_reports`
OPTIONS(description="All 2026 EP field incident reports across state field-report bases. One row per Airtable record. Canonical columns cover the reporter, category, location, and narrative; state-specific fields (incl. subcategories and any voter-identifying fields, which are deliberately NOT canonicalized) stay in the ep_2026_raw typed tables / airtable_records_latest JSON. volunteer_email normalized via norm_email; state comes from the registry.")
AS
SELECT
  'MD' AS state,
  'md_field_report' AS base_key,
  'appl4mIwgXu46SucR' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`report_id` AS report_id,
  t.`volunteer_name` AS volunteer_name,
  t.`volunteer_first_name` AS volunteer_first_name,
  t.`volunteer_last_name` AS volunteer_last_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`volunteer_email`) AS volunteer_email,
  t.`volunteer_email` AS volunteer_email_raw,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`volunteer_s_phone_number`) AS volunteer_phone,
  t.`source` AS source,
  t.`caller` AS caller,
  t.`voting_issue_category` AS category,
  t.`voting_method` AS voting_method,
  t.`polling_place_name_from_polling_place` AS polling_place_name,
  t.`county_from_polling_place` AS county,
  t.`notes_comments` AS description,
  SAFE_CAST(CAST(t.`requires_escalation` AS STRING) AS BOOL) AS requires_escalation,
  SAFE_CAST(CAST(t.`escalation_resolved` AS STRING) AS BOOL) AS escalation_resolved,
  t.`escalation_notes` AS escalation_notes
FROM `proj-tmc-mem-com.ep_2026_raw.md_field_report__incident_reports` t
UNION ALL
SELECT
  'MI' AS state,
  'mi_field_report' AS base_key,
  'appcfBgP8lC85htsQ' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`report_id` AS report_id,
  t.`volunteer_name` AS volunteer_name,
  t.`volunteer_first_name` AS volunteer_first_name,
  t.`volunteer_last_name` AS volunteer_last_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`volunteer_email`) AS volunteer_email,
  t.`volunteer_email` AS volunteer_email_raw,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`volunteer_s_phone_number`) AS volunteer_phone,
  t.`source` AS source,
  t.`caller` AS caller,
  t.`voting_issue_category` AS category,
  t.`voting_method` AS voting_method,
  t.`polling_place_name_from_polling_place` AS polling_place_name,
  t.`county_from_polling_place` AS county,
  t.`notes_comments` AS description,
  SAFE_CAST(CAST(t.`requires_escalation` AS STRING) AS BOOL) AS requires_escalation,
  SAFE_CAST(CAST(t.`escalation_resolved` AS STRING) AS BOOL) AS escalation_resolved,
  t.`escalation_notes` AS escalation_notes
FROM `proj-tmc-mem-com.ep_2026_raw.mi_field_report__incident_reports` t
UNION ALL
SELECT
  'NE' AS state,
  'ne_field_report' AS base_key,
  'app4rdMLSJUpT57Ht' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`report_id` AS report_id,
  t.`volunteer_name` AS volunteer_name,
  t.`volunteer_first_name` AS volunteer_first_name,
  t.`volunteer_last_name` AS volunteer_last_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`volunteer_email`) AS volunteer_email,
  t.`volunteer_email` AS volunteer_email_raw,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`volunteer_s_phone_number`) AS volunteer_phone,
  t.`source` AS source,
  t.`caller` AS caller,
  t.`voting_issue_category` AS category,
  t.`voting_method` AS voting_method,
  t.`polling_place_name_from_polling_place` AS polling_place_name,
  t.`county_from_polling_place` AS county,
  t.`notes_comments` AS description,
  SAFE_CAST(CAST(t.`requires_escalation` AS STRING) AS BOOL) AS requires_escalation,
  SAFE_CAST(CAST(t.`escalation_resolved` AS STRING) AS BOOL) AS escalation_resolved,
  t.`escalation_notes` AS escalation_notes
FROM `proj-tmc-mem-com.ep_2026_raw.ne_field_report__incident_reports` t
UNION ALL
SELECT
  'PA' AS state,
  'pa_field_report' AS base_key,
  'app3EDk60ZEfTR79P' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`report_id` AS report_id,
  t.`volunteer_name` AS volunteer_name,
  t.`volunteer_first_name` AS volunteer_first_name,
  t.`volunteer_last_name` AS volunteer_last_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`volunteer_email`) AS volunteer_email,
  t.`volunteer_email` AS volunteer_email_raw,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`volunteer_s_phone_number`) AS volunteer_phone,
  t.`source` AS source,
  t.`caller` AS caller,
  t.`voting_issue_category` AS category,
  t.`voting_method` AS voting_method,
  t.`polling_place_name_from_polling_place` AS polling_place_name,
  t.`county_from_polling_place` AS county,
  t.`notes_comments` AS description,
  SAFE_CAST(CAST(t.`requires_escalation` AS STRING) AS BOOL) AS requires_escalation,
  SAFE_CAST(CAST(t.`escalation_resolved` AS STRING) AS BOOL) AS escalation_resolved,
  t.`escalation_notes` AS escalation_notes
FROM `proj-tmc-mem-com.ep_2026_raw.pa_field_report__incident_reports` t
UNION ALL
SELECT
  'UT' AS state,
  'ut_field_report' AS base_key,
  'app220U4z726HQ2DY' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`report_id` AS report_id,
  t.`volunteer_name` AS volunteer_name,
  t.`volunteer_first_name` AS volunteer_first_name,
  t.`volunteer_last_name` AS volunteer_last_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`volunteer_email`) AS volunteer_email,
  t.`volunteer_email` AS volunteer_email_raw,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`volunteer_s_phone_number`) AS volunteer_phone,
  t.`source` AS source,
  t.`caller` AS caller,
  t.`voting_issue_category` AS category,
  t.`voting_method` AS voting_method,
  t.`polling_place_name_from_polling_place` AS polling_place_name,
  t.`county_from_polling_place` AS county,
  t.`notes_comments` AS description,
  SAFE_CAST(CAST(t.`requires_escalation` AS STRING) AS BOOL) AS requires_escalation,
  SAFE_CAST(CAST(t.`escalation_resolved` AS STRING) AS BOOL) AS escalation_resolved,
  t.`escalation_notes` AS escalation_notes
FROM `proj-tmc-mem-com.ep_2026_raw.ut_field_report__incident_reports` t
UNION ALL
SELECT
  'WI' AS state,
  'wi_field_report' AS base_key,
  'appbIWiYDwdtuV5so' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`report_id` AS report_id,
  t.`volunteer_name` AS volunteer_name,
  t.`volunteer_first_name` AS volunteer_first_name,
  t.`volunteer_last_name` AS volunteer_last_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`volunteer_email`) AS volunteer_email,
  t.`volunteer_email` AS volunteer_email_raw,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`volunteer_s_phone_number`) AS volunteer_phone,
  t.`source` AS source,
  t.`caller` AS caller,
  t.`voting_issue_category` AS category,
  t.`voting_method` AS voting_method,
  t.`polling_place_name_from_polling_place` AS polling_place_name,
  t.`county_from_polling_place` AS county,
  t.`notes_comments` AS description,
  SAFE_CAST(CAST(t.`requires_escalation` AS STRING) AS BOOL) AS requires_escalation,
  SAFE_CAST(CAST(t.`escalation_resolved` AS STRING) AS BOOL) AS escalation_resolved,
  t.`escalation_notes` AS escalation_notes
FROM `proj-tmc-mem-com.ep_2026_raw.wi_field_report__incident_reports` t;
