-- GENERATED by airtable_views.py -- DO NOT HAND-EDIT.
-- Regenerate with: python apply_bq_views.py --render-generated
-- (sync_airtable_bases.py also re-applies these after every run, so a
-- base going live is included the same morning; refresh + commit this
-- snapshot as part of the go-live checklist.)

CREATE OR REPLACE VIEW `proj-tmc-mem-com.ep_2026_cleaned.checklist_submissions`
OPTIONS(description="All 2026 EP polling-place checklist submissions across state field-report bases (stock 'Checklist Submissions' tables plus bespoke variants like UT's 'Poll Monitoring Checklist'). One row per Airtable record. Volunteer identity resolves from direct fields where the base has them, else via the volunteer record link into that base's Shifted Volunteers table. Per-question answers are NEVER canonicalized across states -- read them from the ep_2026_raw typed tables / airtable_records_latest JSON. state comes from the registry.")
AS
SELECT
  'MD' AS state,
  'md_field_report' AS base_key,
  'appl4mIwgXu46SucR' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`volunteer_email`) AS volunteer_email,
  t.`volunteer_email` AS volunteer_email_raw,
  t.`volunteer_name` AS volunteer_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`volunteer_phone`) AS volunteer_phone,
  pp.`polling_place` AS polling_place,
  pp.`county` AS county,
  t.`polling_place_checklist` AS checklist_name
FROM `proj-tmc-mem-com.ep_2026_raw.md_field_report__checklist_submissions` t
LEFT JOIN `proj-tmc-mem-com.ep_2026_raw.md_field_report__polling_places` pp
  ON pp._airtable_record_id = JSON_VALUE(t.`polling_places`, '$[0]')
UNION ALL
SELECT
  'MI' AS state,
  'mi_field_report' AS base_key,
  'appcfBgP8lC85htsQ' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(sv.`email`) AS volunteer_email,
  sv.`email` AS volunteer_email_raw,
  sv.`full_name` AS volunteer_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(sv.`phone_number`) AS volunteer_phone,
  CAST(NULL AS STRING) AS polling_place,
  CAST(NULL AS STRING) AS county,
  CAST(NULL AS STRING) AS checklist_name
FROM `proj-tmc-mem-com.ep_2026_raw.mi_field_report__checklist_submissions` t
LEFT JOIN `proj-tmc-mem-com.ep_2026_raw.mi_field_report__shifted_volunteers` sv
  ON sv._airtable_record_id = JSON_VALUE(t.`volunteer`, '$[0]')
UNION ALL
SELECT
  'NE' AS state,
  'ne_field_report' AS base_key,
  'app4rdMLSJUpT57Ht' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(sv.`email`) AS volunteer_email,
  sv.`email` AS volunteer_email_raw,
  sv.`full_name` AS volunteer_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(sv.`phone_number`) AS volunteer_phone,
  pp.`polling_place` AS polling_place,
  pp.`county` AS county,
  t.`polling_place_checklist` AS checklist_name
FROM `proj-tmc-mem-com.ep_2026_raw.ne_field_report__checklist_submissions` t
LEFT JOIN `proj-tmc-mem-com.ep_2026_raw.ne_field_report__polling_places` pp
  ON pp._airtable_record_id = JSON_VALUE(t.`polling_places`, '$[0]')
LEFT JOIN `proj-tmc-mem-com.ep_2026_raw.ne_field_report__shifted_volunteers` sv
  ON sv._airtable_record_id = JSON_VALUE(t.`volunteer`, '$[0]')
UNION ALL
SELECT
  'PA' AS state,
  'pa_field_report' AS base_key,
  'app3EDk60ZEfTR79P' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(sv.`email`) AS volunteer_email,
  sv.`email` AS volunteer_email_raw,
  sv.`full_name` AS volunteer_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(sv.`phone_number`) AS volunteer_phone,
  pp.`polling_place` AS polling_place,
  pp.`county` AS county,
  t.`polling_place_checklist` AS checklist_name
FROM `proj-tmc-mem-com.ep_2026_raw.pa_field_report__checklist_submissions` t
LEFT JOIN `proj-tmc-mem-com.ep_2026_raw.pa_field_report__polling_places` pp
  ON pp._airtable_record_id = JSON_VALUE(t.`polling_places`, '$[0]')
LEFT JOIN `proj-tmc-mem-com.ep_2026_raw.pa_field_report__shifted_volunteers` sv
  ON sv._airtable_record_id = JSON_VALUE(t.`volunteer`, '$[0]')
UNION ALL
SELECT
  'UT' AS state,
  'ut_field_report' AS base_key,
  'app220U4z726HQ2DY' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  CAST(NULL AS STRING) AS volunteer_email,
  CAST(NULL AS STRING) AS volunteer_email_raw,
  t.`volunteer_name` AS volunteer_name,
  CAST(NULL AS STRING) AS volunteer_phone,
  t.`polling_place` AS polling_place,
  t.`county` AS county,
  CAST(NULL AS STRING) AS checklist_name
FROM `proj-tmc-mem-com.ep_2026_raw.ut_field_report__poll_monitoring_checklist` t
UNION ALL
SELECT
  'WI' AS state,
  'wi_field_report' AS base_key,
  'appbIWiYDwdtuV5so' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(sv.`email`) AS volunteer_email,
  sv.`email` AS volunteer_email_raw,
  sv.`full_name` AS volunteer_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(sv.`phone_number`) AS volunteer_phone,
  pp.`polling_place` AS polling_place,
  pp.`county` AS county,
  t.`polling_place_checklist` AS checklist_name
FROM `proj-tmc-mem-com.ep_2026_raw.wi_field_report__checklist_submissions` t
LEFT JOIN `proj-tmc-mem-com.ep_2026_raw.wi_field_report__polling_places` pp
  ON pp._airtable_record_id = JSON_VALUE(t.`polling_places`, '$[0]')
LEFT JOIN `proj-tmc-mem-com.ep_2026_raw.wi_field_report__shifted_volunteers` sv
  ON sv._airtable_record_id = JSON_VALUE(t.`volunteer`, '$[0]');
