-- GENERATED by airtable_views.py -- DO NOT HAND-EDIT.
-- Regenerate with: python apply_bq_views.py --render-generated
-- (sync_airtable_bases.py also re-applies these after every run, so a
-- base going live is included the same morning; refresh + commit this
-- snapshot as part of the go-live checklist.)

CREATE OR REPLACE VIEW `proj-tmc-mem-com.ep_2026_cleaned.polling_places`
OPTIONS(description="All polling places loaded into the state field-report bases (CC-loaded reference data plus any field additions). One row per Airtable record. state comes from the registry.")
AS
SELECT
  'MD' AS state,
  'md_field_report' AS base_key,
  'appl4mIwgXu46SucR' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`polling_place` AS name,
  t.`pp_name` AS pp_name,
  t.`address` AS address,
  t.`city` AS city,
  t.`zip` AS zip_code,
  t.`county` AS county,
  t.`location_notes` AS notes
FROM `proj-tmc-mem-com.ep_2026_raw.md_field_report__polling_places` t
UNION ALL
SELECT
  'MI' AS state,
  'mi_field_report' AS base_key,
  'appcfBgP8lC85htsQ' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`polling_place` AS name,
  t.`pp_name` AS pp_name,
  t.`address` AS address,
  t.`city` AS city,
  t.`zip` AS zip_code,
  t.`county` AS county,
  t.`location_notes` AS notes
FROM `proj-tmc-mem-com.ep_2026_raw.mi_field_report__polling_places` t
UNION ALL
SELECT
  'NE' AS state,
  'ne_field_report' AS base_key,
  'app4rdMLSJUpT57Ht' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`polling_place` AS name,
  t.`pp_name` AS pp_name,
  t.`address` AS address,
  t.`city` AS city,
  t.`zip` AS zip_code,
  t.`county` AS county,
  t.`location_notes` AS notes
FROM `proj-tmc-mem-com.ep_2026_raw.ne_field_report__polling_places` t
UNION ALL
SELECT
  'PA' AS state,
  'pa_field_report' AS base_key,
  'app3EDk60ZEfTR79P' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`polling_place` AS name,
  t.`pp_name` AS pp_name,
  t.`address` AS address,
  t.`city` AS city,
  t.`zip` AS zip_code,
  t.`county` AS county,
  t.`location_notes` AS notes
FROM `proj-tmc-mem-com.ep_2026_raw.pa_field_report__polling_places` t
UNION ALL
SELECT
  'UT' AS state,
  'ut_field_report' AS base_key,
  'app220U4z726HQ2DY' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`polling_place` AS name,
  t.`pp_name` AS pp_name,
  t.`address` AS address,
  t.`city` AS city,
  t.`zip` AS zip_code,
  t.`county` AS county,
  t.`location_notes` AS notes
FROM `proj-tmc-mem-com.ep_2026_raw.ut_field_report__polling_places` t
UNION ALL
SELECT
  'WI' AS state,
  'wi_field_report' AS base_key,
  'appbIWiYDwdtuV5so' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  t.`polling_place` AS name,
  t.`pp_name` AS pp_name,
  t.`address` AS address,
  t.`city` AS city,
  t.`zip` AS zip_code,
  t.`county` AS county,
  t.`location_notes` AS notes
FROM `proj-tmc-mem-com.ep_2026_raw.wi_field_report__polling_places` t;
