-- GENERATED by airtable_views.py -- DO NOT HAND-EDIT.
-- Regenerate with: python apply_bq_views.py --render-generated
-- (sync_airtable_bases.py also re-applies these after every run, so a
-- base going live is included the same morning; refresh + commit this
-- snapshot as part of the go-live checklist.)

CREATE OR REPLACE VIEW `proj-tmc-mem-com.ep_2026_cleaned.shifted_volunteers`
OPTIONS(description="All records in the state bases' 'Shifted Volunteers' tables (dual write paths: the PTV sync upsert + the emergency self-add form). One row per Airtable record. in_ptv flags whether the (state, email) exists in PTV's CURRENT roster (ptv_raw_2026.v_users_current) -- FALSE means a self-add with no PTV counterpart yet. Feeds the volunteers view's self-add branch; also useful for sync reconciliation. email/phone normalized; state comes from the registry.")
AS
SELECT
  'MD' AS state,
  'md_field_report' AS base_key,
  'appl4mIwgXu46SucR' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`first_name` AS first_name,
  t.`last_name` AS last_name,
  t.`full_name` AS full_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`phone_number`) AS phone,
  t.`county` AS county,
  t.`zip` AS zip_code,
  t.`unique_id_column` AS unique_id,
  EXISTS(SELECT 1 FROM `proj-tmc-mem-com.ptv_raw_2026.v_users_current` u WHERE u.state = 'MD' AND u.email = `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`)) AS in_ptv
FROM `proj-tmc-mem-com.ep_2026_raw.md_field_report__shifted_volunteers` t
UNION ALL
SELECT
  'MI' AS state,
  'mi_field_report' AS base_key,
  'appcfBgP8lC85htsQ' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`first_name` AS first_name,
  t.`last_name` AS last_name,
  t.`full_name` AS full_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`phone_number`) AS phone,
  t.`county` AS county,
  t.`zip` AS zip_code,
  t.`unique_id_column` AS unique_id,
  EXISTS(SELECT 1 FROM `proj-tmc-mem-com.ptv_raw_2026.v_users_current` u WHERE u.state = 'MI' AND u.email = `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`)) AS in_ptv
FROM `proj-tmc-mem-com.ep_2026_raw.mi_field_report__shifted_volunteers` t
UNION ALL
SELECT
  'NE' AS state,
  'ne_field_report' AS base_key,
  'app4rdMLSJUpT57Ht' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`first_name` AS first_name,
  t.`last_name` AS last_name,
  t.`full_name` AS full_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`phone_number`) AS phone,
  t.`county` AS county,
  t.`zip` AS zip_code,
  t.`unique_id_column` AS unique_id,
  EXISTS(SELECT 1 FROM `proj-tmc-mem-com.ptv_raw_2026.v_users_current` u WHERE u.state = 'NE' AND u.email = `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`)) AS in_ptv
FROM `proj-tmc-mem-com.ep_2026_raw.ne_field_report__shifted_volunteers` t
UNION ALL
SELECT
  'PA' AS state,
  'pa_field_report' AS base_key,
  'app3EDk60ZEfTR79P' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`first_name` AS first_name,
  t.`last_name` AS last_name,
  t.`full_name` AS full_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`phone_number`) AS phone,
  t.`county` AS county,
  t.`zip` AS zip_code,
  t.`unique_id_column` AS unique_id,
  EXISTS(SELECT 1 FROM `proj-tmc-mem-com.ptv_raw_2026.v_users_current` u WHERE u.state = 'PA' AND u.email = `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`)) AS in_ptv
FROM `proj-tmc-mem-com.ep_2026_raw.pa_field_report__shifted_volunteers` t
UNION ALL
SELECT
  'UT' AS state,
  'ut_field_report' AS base_key,
  'app220U4z726HQ2DY' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`first_name` AS first_name,
  t.`last_name` AS last_name,
  t.`full_name` AS full_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`phone_number`) AS phone,
  t.`county` AS county,
  t.`zip` AS zip_code,
  t.`unique_id_column` AS unique_id,
  EXISTS(SELECT 1 FROM `proj-tmc-mem-com.ptv_raw_2026.v_users_current` u WHERE u.state = 'UT' AND u.email = `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`)) AS in_ptv
FROM `proj-tmc-mem-com.ep_2026_raw.ut_field_report__shifted_volunteers` t
UNION ALL
SELECT
  'WI' AS state,
  'wi_field_report' AS base_key,
  'appbIWiYDwdtuV5so' AS base_id,
  t._airtable_record_id AS record_id,
  t._airtable_created_time AS created_at,
  t._synced_at AS synced_at,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`) AS email,
  t.`email` AS email_raw,
  t.`first_name` AS first_name,
  t.`last_name` AS last_name,
  t.`full_name` AS full_name,
  `proj-tmc-mem-com.ep_2026_cleaned.norm_phone`(t.`phone_number`) AS phone,
  t.`county` AS county,
  t.`zip` AS zip_code,
  t.`unique_id_column` AS unique_id,
  EXISTS(SELECT 1 FROM `proj-tmc-mem-com.ptv_raw_2026.v_users_current` u WHERE u.state = 'WI' AND u.email = `proj-tmc-mem-com.ep_2026_cleaned.norm_email`(t.`email`)) AS in_ptv
FROM `proj-tmc-mem-com.ep_2026_raw.wi_field_report__shifted_volunteers` t;
